package com.coconason.dtf.demo2.dao;

import com.coconason.dtf.demo2.po.Sc;
import com.coconason.dtf.demo2.po.ScExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface ScMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    int countByExample(ScExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    int deleteByExample(ScExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    int insert(Sc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    int insertSelective(Sc record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    List<Sc> selectByExample(ScExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sc record, @Param("example") ScExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    int updateByExample(@Param("record") Sc record, @Param("example") ScExample example);
}