package com.coconason.dtf.manager.po;

import java.io.Serializable;

public class Sc implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sc.S
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private Integer s;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sc.C
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private Integer c;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Sc.score
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Sc
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sc.S
     *
     * @return the value of Sc.S
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public Integer getS() {
        return s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sc.S
     *
     * @param s the value for Sc.S
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public void setS(Integer s) {
        this.s = s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sc.C
     *
     * @return the value of Sc.C
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public Integer getC() {
        return c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sc.C
     *
     * @param c the value for Sc.C
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public void setC(Integer c) {
        this.c = c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Sc.score
     *
     * @return the value of Sc.score
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Sc.score
     *
     * @param score the value for Sc.score
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public void setScore(Integer score) {
        this.score = score;
    }
}