package com.coconason.dtf.demo3.po;

import java.io.Serializable;

public class Student implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.S
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private Integer s;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Sname
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Sage
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private Integer sage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.Ssex
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private String ssex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Student
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.S
     *
     * @return the value of Student.S
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public Integer getS() {
        return s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.S
     *
     * @param s the value for Student.S
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public void setS(Integer s) {
        this.s = s;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Sname
     *
     * @return the value of Student.Sname
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Sname
     *
     * @param sname the value for Student.Sname
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Sage
     *
     * @return the value of Student.Sage
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public Integer getSage() {
        return sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Sage
     *
     * @param sage the value for Student.Sage
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public void setSage(Integer sage) {
        this.sage = sage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.Ssex
     *
     * @return the value of Student.Ssex
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public String getSsex() {
        return ssex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.Ssex
     *
     * @param ssex the value for Student.Ssex
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public void setSsex(String ssex) {
        this.ssex = ssex == null ? null : ssex.trim();
    }
}