package com.dtf.demo.po;

import java.util.ArrayList;
import java.util.List;

public class CourseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Course
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Course
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Course
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public CourseExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @param orderByClause String
     */
    public void setOrderByClause(final String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @return orderByClause String
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @param distinct boolean
     */
    public void setDistinct(final boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @return distinct boolean
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @return list of criteria
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @param criteria Criteria
     */
    public void or(final Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @return criteria of or
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @return criteria
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     *
     * @return criteria
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Course
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Course
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        
        private List<Criterion> criteria;
        
        private GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }
        
        /**
         * Check whether the size of criteria is valid.
         * 
         * @return whether size greater than 0
         */
        public boolean isValid() {
            return criteria.size() > 0;
        }

        /**
         * Get all criteria.
         * 
         * @return list of criterion
         */
        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        /**
         * Get criteria.
         * 
         * @return list of criterion
         */
        public List<Criterion> getCriteria() {
            return criteria;
        }

        private void addCriterion(final String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        private void addCriterion(final String condition, final Object value, final String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        private void addCriterion(final String condition, final Object value1, final Object value2, final String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }
        
        public Criteria andCIsNull() {
            addCriterion("C is null");
            return (Criteria) this;
        }
        
        public Criteria andCIsNotNull() {
            addCriterion("C is not null");
            return (Criteria) this;
        }
        
        public Criteria andCEqualTo(final Integer value) {
            addCriterion("C =", value, "c");
            return (Criteria) this;
        }
        
        public Criteria andCNotEqualTo(final Integer value) {
            addCriterion("C <>", value, "c");
            return (Criteria) this;
        }
        
        public Criteria andCGreaterThan(final Integer value) {
            addCriterion("C >", value, "c");
            return (Criteria) this;
        }
        
        public Criteria andCGreaterThanOrEqualTo(final Integer value) {
            addCriterion("C >=", value, "c");
            return (Criteria) this;
        }
        
        public Criteria andCLessThan(final Integer value) {
            addCriterion("C <", value, "c");
            return (Criteria) this;
        }
        
        public Criteria andCLessThanOrEqualTo(final Integer value) {
            addCriterion("C <=", value, "c");
            return (Criteria) this;
        }
        
        public Criteria andCIn(final List<Integer> values) {
            addCriterion("C in", values, "c");
            return (Criteria) this;
        }
        
        public Criteria andCNotIn(final List<Integer> values) {
            addCriterion("C not in", values, "c");
            return (Criteria) this;
        }
        
        public Criteria andCBetween(final Integer value1, final Integer value2) {
            addCriterion("C between", value1, value2, "c");
            return (Criteria) this;
        }
        
        public Criteria andCNotBetween(final Integer value1, final Integer value2) {
            addCriterion("C not between", value1, value2, "c");
            return (Criteria) this;
        }
        
        public Criteria andCnameIsNull() {
            addCriterion("Cname is null");
            return (Criteria) this;
        }
        
        public Criteria andCnameIsNotNull() {
            addCriterion("Cname is not null");
            return (Criteria) this;
        }
        
        public Criteria andCnameEqualTo(final String value) {
            addCriterion("Cname =", value, "cname");
            return (Criteria) this;
        }
        
        public Criteria andCnameNotEqualTo(final String value) {
            addCriterion("Cname <>", value, "cname");
            return (Criteria) this;
        }
        
        public Criteria andCnameGreaterThan(final String value) {
            addCriterion("Cname >", value, "cname");
            return (Criteria) this;
        }
        
        public Criteria andCnameGreaterThanOrEqualTo(final String value) {
            addCriterion("Cname >=", value, "cname");
            return (Criteria) this;
        }
        
        public Criteria andCnameLessThan(final String value) {
            addCriterion("Cname <", value, "cname");
            return (Criteria) this;
        }
        
        public Criteria andCnameLessThanOrEqualTo(final String value) {
            addCriterion("Cname <=", value, "cname");
            return (Criteria) this;
        }
        
        public Criteria andCnameLike(final String value) {
            addCriterion("Cname like", value, "cname");
            return (Criteria) this;
        }
        
        public Criteria andCnameNotLike(final String value) {
            addCriterion("Cname not like", value, "cname");
            return (Criteria) this;
        }
        
        public Criteria andCnameIn(final List<String> values) {
            addCriterion("Cname in", values, "cname");
            return (Criteria) this;
        }
        
        public Criteria andCnameNotIn(final List<String> values) {
            addCriterion("Cname not in", values, "cname");
            return (Criteria) this;
        }
        
        public Criteria andCnameBetween(final String value1, final String value2) {
            addCriterion("Cname between", value1, value2, "cname");
            return (Criteria) this;
        }
        
        public Criteria andCnameNotBetween(final String value1, final String value2) {
            addCriterion("Cname not between", value1, value2, "cname");
            return (Criteria) this;
        }
        
        public Criteria andTIsNull() {
            addCriterion("T is null");
            return (Criteria) this;
        }
        
        public Criteria andTIsNotNull() {
            addCriterion("T is not null");
            return (Criteria) this;
        }
        
        public Criteria andTEqualTo(final Integer value) {
            addCriterion("T =", value, "t");
            return (Criteria) this;
        }
        
        public Criteria andTNotEqualTo(final Integer value) {
            addCriterion("T <>", value, "t");
            return (Criteria) this;
        }
        
        public Criteria andTGreaterThan(final Integer value) {
            addCriterion("T >", value, "t");
            return (Criteria) this;
        }
        
        public Criteria andTGreaterThanOrEqualTo(final Integer value) {
            addCriterion("T >=", value, "t");
            return (Criteria) this;
        }
        
        public Criteria andTLessThan(final Integer value) {
            addCriterion("T <", value, "t");
            return (Criteria) this;
        }
        
        public Criteria andTLessThanOrEqualTo(final Integer value) {
            addCriterion("T <=", value, "t");
            return (Criteria) this;
        }
        
        public Criteria andTIn(final List<Integer> values) {
            addCriterion("T in", values, "t");
            return (Criteria) this;
        }
        
        public Criteria andTNotIn(final List<Integer> values) {
            addCriterion("T not in", values, "t");
            return (Criteria) this;
        }
        
        public Criteria andTBetween(final Integer value1, final Integer value2) {
            addCriterion("T between", value1, value2, "t");
            return (Criteria) this;
        }
        
        public Criteria andTNotBetween(final Integer value1, final Integer value2) {
            addCriterion("T not between", value1, value2, "t");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Course
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 27 14:24:30 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Course
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public static final class Criterion {
        
        private String condition;
        
        private Object value;
        
        private Object secondValue;
        
        private boolean noValue;
        
        private boolean singleValue;
        
        private boolean betweenValue;
        
        private boolean listValue;
        
        private String typeHandler;
        
        private Criterion(final String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }
        
        private Criterion(final String condition, final Object value, final String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }
        
        private Criterion(final String condition, final Object value) {
            this(condition, value, null);
        }
        
        private Criterion(final String condition, final Object value, final Object secondValue, final String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }
        
        private Criterion(final String condition, final Object value, final Object secondValue) {
            this(condition, value, secondValue, null);
        }
        
        /**
         * Get condition.
         *
         * @return condition
         */
        public String getCondition() {
            return condition;
        }
        
        /**
         * Get value.
         *
         * @return value.
         */
        public Object getValue() {
            return value;
        }
        
        /**
         * Get second value.
         *
         * @return secondValue.
         */
        public Object getSecondValue() {
            return secondValue;
        }
        
        /**
         * Is not value.
         *
         * @return noValue
         */
        public boolean isNoValue() {
            return noValue;
        }
        
        /**
         * Is single value.
         *
         * @return singleValue
         */
        public boolean isSingleValue() {
            return singleValue;
        }
        
        /**
         * Is between value.
         *
         * @return betweenValue
         */
        public boolean isBetweenValue() {
            return betweenValue;
        }
        
        /**
         * Is list value.
         *
         * @return listValue
         */
        public boolean isListValue() {
            return listValue;
        }
        
        /**
         * Get type handler.
         *
         * @return typeHandler
         */
        public String getTypeHandler() {
            return typeHandler;
        }
    }
    
}
