package com.coconason.dtf.demo2.po;

import java.util.ArrayList;
import java.util.List;

public class ScExample {
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Sc
     */
    private String orderByClause;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Sc
     */
    private boolean distinct;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Sc
     */
    private List<Criteria> oredCriteria;
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     */
    public ScExample() {
        oredCriteria = new ArrayList<Criteria>();
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     * 
     * @param orderByClause String
     */
    public void setOrderByClause(final String orderByClause) {
        this.orderByClause = orderByClause;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     * 
     * @return orderByClause
     */
    public String getOrderByClause() {
        return orderByClause;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     * 
     * @param distinct boolean
     */
    public void setDistinct(final boolean distinct) {
        this.distinct = distinct;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     * 
     * @return whether is distinct
     */
    public boolean isDistinct() {
        return distinct;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     * 
     * @return list of criteria
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     * 
     * @param criteria Criteria
     */
    public void or(final Criteria criteria) {
        oredCriteria.add(criteria);
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     * 
     * @return criteria Criteria
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     * 
     * @return criteria
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Sc
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }
    
    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Sc
     */
    protected abstract static class GeneratedCriteria {
        
        private List<Criterion> criteria;

        private GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }
        
        public boolean isValid() {
            return criteria.size() > 0;
        }
        
        public List<Criterion> getAllCriteria() {
            return criteria;
        }
        
        public List<Criterion> getCriteria() {
            return criteria;
        }

        private void addCriterion(final String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        private void addCriterion(final String condition, final Object value, final String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        private void addCriterion(final String condition, final Object value1, final Object value2, final String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSIsNull() {
            addCriterion("S is null");
            return (Criteria) this;
        }

        public Criteria andSIsNotNull() {
            addCriterion("S is not null");
            return (Criteria) this;
        }

        public Criteria andSEqualTo(final Integer value) {
            addCriterion("S =", value, "s");
            return (Criteria) this;
        }

        public Criteria andSNotEqualTo(final Integer value) {
            addCriterion("S <>", value, "s");
            return (Criteria) this;
        }

        public Criteria andSGreaterThan(final Integer value) {
            addCriterion("S >", value, "s");
            return (Criteria) this;
        }

        public Criteria andSGreaterThanOrEqualTo(final Integer value) {
            addCriterion("S >=", value, "s");
            return (Criteria) this;
        }

        public Criteria andSLessThan(final Integer value) {
            addCriterion("S <", value, "s");
            return (Criteria) this;
        }

        public Criteria andSLessThanOrEqualTo(final Integer value) {
            addCriterion("S <=", value, "s");
            return (Criteria) this;
        }

        public Criteria andSIn(final List<Integer> values) {
            addCriterion("S in", values, "s");
            return (Criteria) this;
        }

        public Criteria andSNotIn(final List<Integer> values) {
            addCriterion("S not in", values, "s");
            return (Criteria) this;
        }

        public Criteria andSBetween(final Integer value1, final Integer value2) {
            addCriterion("S between", value1, value2, "s");
            return (Criteria) this;
        }

        public Criteria andSNotBetween(final Integer value1, final Integer value2) {
            addCriterion("S not between", value1, value2, "s");
            return (Criteria) this;
        }

        public Criteria andCIsNull() {
            addCriterion("C is null");
            return (Criteria) this;
        }

        public Criteria andCIsNotNull() {
            addCriterion("C is not null");
            return (Criteria) this;
        }

        public Criteria andCEqualTo(final Integer value) {
            addCriterion("C =", value, "c");
            return (Criteria) this;
        }

        public Criteria andCNotEqualTo(final Integer value) {
            addCriterion("C <>", value, "c");
            return (Criteria) this;
        }

        public Criteria andCGreaterThan(final Integer value) {
            addCriterion("C >", value, "c");
            return (Criteria) this;
        }

        public Criteria andCGreaterThanOrEqualTo(final Integer value) {
            addCriterion("C >=", value, "c");
            return (Criteria) this;
        }

        public Criteria andCLessThan(final Integer value) {
            addCriterion("C <", value, "c");
            return (Criteria) this;
        }

        public Criteria andCLessThanOrEqualTo(final Integer value) {
            addCriterion("C <=", value, "c");
            return (Criteria) this;
        }

        public Criteria andCIn(final List<Integer> values) {
            addCriterion("C in", values, "c");
            return (Criteria) this;
        }

        public Criteria andCNotIn(final List<Integer> values) {
            addCriterion("C not in", values, "c");
            return (Criteria) this;
        }

        public Criteria andCBetween(final Integer value1, final Integer value2) {
            addCriterion("C between", value1, value2, "c");
            return (Criteria) this;
        }

        public Criteria andCNotBetween(final Integer value1, final Integer value2) {
            addCriterion("C not between", value1, value2, "c");
            return (Criteria) this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return (Criteria) this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return (Criteria) this;
        }

        public Criteria andScoreEqualTo(final Integer value) {
            addCriterion("score =", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotEqualTo(final Integer value) {
            addCriterion("score <>", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThan(final Integer value) {
            addCriterion("score >", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(final Integer value) {
            addCriterion("score >=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThan(final Integer value) {
            addCriterion("score <", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreLessThanOrEqualTo(final Integer value) {
            addCriterion("score <=", value, "score");
            return (Criteria) this;
        }

        public Criteria andScoreIn(final List<Integer> values) {
            addCriterion("score in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotIn(final List<Integer> values) {
            addCriterion("score not in", values, "score");
            return (Criteria) this;
        }

        public Criteria andScoreBetween(final Integer value1, final Integer value2) {
            addCriterion("score between", value1, value2, "score");
            return (Criteria) this;
        }

        public Criteria andScoreNotBetween(final Integer value1, final Integer value2) {
            addCriterion("score not between", value1, value2, "score");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Sc
     *
     * @mbggenerated do_not_delete_during_merge Mon Aug 27 14:24:30 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table Sc
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public static final class Criterion {

        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        private Criterion(final String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        private Criterion(final String condition, final Object value, final String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        private Criterion(final String condition, final Object value) {
            this(condition, value, null);
        }

        private Criterion(final String condition, final Object value, final Object secondValue, final String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        private Criterion(final String condition, final Object value, final Object secondValue) {
            this(condition, value, secondValue, null);
        }

        /**
         * Get condition.
         *
         * @return condition
         */
        public String getCondition() {
            return condition;
        }

        /**
         * Get value.
         *
         * @return value.
         */
        public Object getValue() {
            return value;
        }

        /**
         * Get second value.
         *
         * @return secondValue.
         */
        public Object getSecondValue() {
            return secondValue;
        }

        /**
         * Is not value.
         *
         * @return noValue
         */
        public boolean isNoValue() {
            return noValue;
        }

        /**
         * Is single value.
         *
         * @return singleValue
         */
        public boolean isSingleValue() {
            return singleValue;
        }

        /**
         * Is between value.
         *
         * @return betweenValue
         */
        public boolean isBetweenValue() {
            return betweenValue;
        }

        /**
         * Is list value.
         *
         * @return listValue
         */
        public boolean isListValue() {
            return listValue;
        }

        /**
         * Get type handler.
         *
         * @return typeHandler
         */
        public String getTypeHandler() {
            return typeHandler;
        }
        
    }
    
}
