// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.coconason.dtf.common.protobuf;
/**
 * @Author: Jason
 * @date: 2018/10/11-10:58
 */

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 crcCode = 1;
    /**
     * <code>optional int32 crcCode = 1;</code>
     */
    boolean hasCrcCode();
    /**
     * <code>optional int32 crcCode = 1;</code>
     */
    int getCrcCode();

    // optional int32 length = 2;
    /**
     * <code>optional int32 length = 2;</code>
     */
    boolean hasLength();
    /**
     * <code>optional int32 length = 2;</code>
     */
    int getLength();

    // optional int64 sessionID = 3;
    /**
     * <code>optional int64 sessionID = 3;</code>
     */
    boolean hasSessionID();
    /**
     * <code>optional int64 sessionID = 3;</code>
     */
    long getSessionID();

    // optional int32 type = 4;
    /**
     * <code>optional int32 type = 4;</code>
     */
    boolean hasType();
    /**
     * <code>optional int32 type = 4;</code>
     */
    int getType();

    // optional int32 priority = 5;
    /**
     * <code>optional int32 priority = 5;</code>
     */
    boolean hasPriority();
    /**
     * <code>optional int32 priority = 5;</code>
     */
    int getPriority();

    // optional string id = 6;
    /**
     * <code>optional string id = 6;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 6;</code>
     */
    String getId();
    /**
     * <code>optional string id = 6;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // optional string info = 7;
    /**
     * <code>optional string info = 7;</code>
     */
    boolean hasInfo();
    /**
     * <code>optional string info = 7;</code>
     */
    String getInfo();
    /**
     * <code>optional string info = 7;</code>
     */
    com.google.protobuf.ByteString
        getInfoBytes();

    // optional .Message.ActionType action = 8 [default = DEFAULT];
    /**
     * <code>optional .Message.ActionType action = 8 [default = DEFAULT];</code>
     */
    boolean hasAction();
    /**
     * <code>optional .Message.ActionType action = 8 [default = DEFAULT];</code>
     */
    Message.ActionType getAction();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              crcCode_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              length_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              sessionID_ = input.readInt64();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              type_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              priority_ = input.readInt32();
              break;
            }
            case 50: {
              bitField0_ |= 0x00000020;
              id_ = input.readBytes();
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              info_ = input.readBytes();
              break;
            }
            case 64: {
              int rawValue = input.readEnum();
              ActionType value = ActionType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(8, rawValue);
              } else {
                bitField0_ |= 0x00000080;
                action_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProto.internal_static_Message_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProto.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code Message.ActionType}
     */
    public enum ActionType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>ADD = 1;</code>
       */
      ADD(0, 1),
      /**
       * <code>APPLYFORSUBMIT = 2;</code>
       */
      APPLYFORSUBMIT(1, 2),
      /**
       * <code>APPROVESUBMIT = 3;</code>
       */
      APPROVESUBMIT(2, 3),
      /**
       * <code>CANCEL = 4;</code>
       */
      CANCEL(3, 4),
      /**
       * <code>SUCCESS = 5;</code>
       */
      SUCCESS(4, 5),
      /**
       * <code>FAIL = 6;</code>
       */
      FAIL(5, 6),
      /**
       * <code>DEFAULT = 7;</code>
       */
      DEFAULT(6, 7),
      /**
       * <code>LOGIN_REQ = 8;</code>
       */
      LOGIN_REQ(7, 8),
      /**
       * <code>LOGIN_RESP = 9;</code>
       */
      LOGIN_RESP(8, 9),
      /**
       * <code>HEARTBEAT_REQ = 10;</code>
       */
      HEARTBEAT_REQ(9, 10),
      /**
       * <code>HEARTBEAT_RESP = 11;</code>
       */
      HEARTBEAT_RESP(10, 11),
      /**
       * <code>ADD_STRONG = 12;</code>
       */
      ADD_STRONG(11, 12),
      /**
       * <code>APPLYFORSUBMIT_STRONG = 13;</code>
       */
      APPLYFORSUBMIT_STRONG(12, 13),
      /**
       * <code>APPROVESUBMIT_STRONG = 14;</code>
       */
      APPROVESUBMIT_STRONG(13, 14),
      /**
       * <code>SUB_SUCCESS_STRONG = 15;</code>
       */
      SUB_SUCCESS_STRONG(14, 15),
      /**
       * <code>SUB_FAIL_STRONG = 16;</code>
       */
      SUB_FAIL_STRONG(15, 16),
      /**
       * <code>WHOLE_SUCCESS_STRONG = 17;</code>
       */
      WHOLE_SUCCESS_STRONG(16, 17),
      /**
       * <code>WHOLE_FAIL_STRONG = 18;</code>
       */
      WHOLE_FAIL_STRONG(17, 18),
      /**
       * <code>ADD_ASYNC = 19;</code>
       */
      ADD_ASYNC(18, 19),
      /**
       * <code>ADD_SUCCESS_ASYNC = 20;</code>
       */
      ADD_SUCCESS_ASYNC(19, 20),
      /**
       * <code>ADD_FAIL_ASYNC = 21;</code>
       */
      ADD_FAIL_ASYNC(20, 21),
      /**
       * <code>ASYNC_COMMIT = 22;</code>
       */
      ASYNC_COMMIT(21, 22),
      /**
       * <code>ASYNC_CANCEL = 23;</code>
       */
      ASYNC_CANCEL(22, 23),
      /**
       * <code>COMMIT_SUCCESS_ASYNC = 24;</code>
       */
      COMMIT_SUCCESS_ASYNC(23, 24),
      /**
       * <code>WHOLE_SUCCESS_STRONG_ACK = 25;</code>
       */
      WHOLE_SUCCESS_STRONG_ACK(24, 25),
      /**
       * <code>WHOLE_FAIL_STRONG_ACK = 26;</code>
       */
      WHOLE_FAIL_STRONG_ACK(25, 26),
      /**
       * <code>SUB_SUCCESS = 27;</code>
       */
      SUB_SUCCESS(26, 27),
      /**
       * <code>SUB_FAIL = 28;</code>
       */
      SUB_FAIL(27, 28),
      ;

      /**
       * <code>ADD = 1;</code>
       */
      public static final int ADD_VALUE = 1;
      /**
       * <code>APPLYFORSUBMIT = 2;</code>
       */
      public static final int APPLYFORSUBMIT_VALUE = 2;
      /**
       * <code>APPROVESUBMIT = 3;</code>
       */
      public static final int APPROVESUBMIT_VALUE = 3;
      /**
       * <code>CANCEL = 4;</code>
       */
      public static final int CANCEL_VALUE = 4;
      /**
       * <code>SUCCESS = 5;</code>
       */
      public static final int SUCCESS_VALUE = 5;
      /**
       * <code>FAIL = 6;</code>
       */
      public static final int FAIL_VALUE = 6;
      /**
       * <code>DEFAULT = 7;</code>
       */
      public static final int DEFAULT_VALUE = 7;
      /**
       * <code>LOGIN_REQ = 8;</code>
       */
      public static final int LOGIN_REQ_VALUE = 8;
      /**
       * <code>LOGIN_RESP = 9;</code>
       */
      public static final int LOGIN_RESP_VALUE = 9;
      /**
       * <code>HEARTBEAT_REQ = 10;</code>
       */
      public static final int HEARTBEAT_REQ_VALUE = 10;
      /**
       * <code>HEARTBEAT_RESP = 11;</code>
       */
      public static final int HEARTBEAT_RESP_VALUE = 11;
      /**
       * <code>ADD_STRONG = 12;</code>
       */
      public static final int ADD_STRONG_VALUE = 12;
      /**
       * <code>APPLYFORSUBMIT_STRONG = 13;</code>
       */
      public static final int APPLYFORSUBMIT_STRONG_VALUE = 13;
      /**
       * <code>APPROVESUBMIT_STRONG = 14;</code>
       */
      public static final int APPROVESUBMIT_STRONG_VALUE = 14;
      /**
       * <code>SUB_SUCCESS_STRONG = 15;</code>
       */
      public static final int SUB_SUCCESS_STRONG_VALUE = 15;
      /**
       * <code>SUB_FAIL_STRONG = 16;</code>
       */
      public static final int SUB_FAIL_STRONG_VALUE = 16;
      /**
       * <code>WHOLE_SUCCESS_STRONG = 17;</code>
       */
      public static final int WHOLE_SUCCESS_STRONG_VALUE = 17;
      /**
       * <code>WHOLE_FAIL_STRONG = 18;</code>
       */
      public static final int WHOLE_FAIL_STRONG_VALUE = 18;
      /**
       * <code>ADD_ASYNC = 19;</code>
       */
      public static final int ADD_ASYNC_VALUE = 19;
      /**
       * <code>ADD_SUCCESS_ASYNC = 20;</code>
       */
      public static final int ADD_SUCCESS_ASYNC_VALUE = 20;
      /**
       * <code>ADD_FAIL_ASYNC = 21;</code>
       */
      public static final int ADD_FAIL_ASYNC_VALUE = 21;
      /**
       * <code>ASYNC_COMMIT = 22;</code>
       */
      public static final int ASYNC_COMMIT_VALUE = 22;
      /**
       * <code>ASYNC_CANCEL = 23;</code>
       */
      public static final int ASYNC_CANCEL_VALUE = 23;
      /**
       * <code>COMMIT_SUCCESS_ASYNC = 24;</code>
       */
      public static final int COMMIT_SUCCESS_ASYNC_VALUE = 24;
      /**
       * <code>WHOLE_SUCCESS_STRONG_ACK = 25;</code>
       */
      public static final int WHOLE_SUCCESS_STRONG_ACK_VALUE = 25;
      /**
       * <code>WHOLE_FAIL_STRONG_ACK = 26;</code>
       */
      public static final int WHOLE_FAIL_STRONG_ACK_VALUE = 26;
      /**
       * <code>SUB_SUCCESS = 27;</code>
       */
      public static final int SUB_SUCCESS_VALUE = 27;
      /**
       * <code>SUB_FAIL = 28;</code>
       */
      public static final int SUB_FAIL_VALUE = 28;


      public final int getNumber() { return value; }

      public static ActionType valueOf(int value) {
        switch (value) {
          case 1: return ADD;
          case 2: return APPLYFORSUBMIT;
          case 3: return APPROVESUBMIT;
          case 4: return CANCEL;
          case 5: return SUCCESS;
          case 6: return FAIL;
          case 7: return DEFAULT;
          case 8: return LOGIN_REQ;
          case 9: return LOGIN_RESP;
          case 10: return HEARTBEAT_REQ;
          case 11: return HEARTBEAT_RESP;
          case 12: return ADD_STRONG;
          case 13: return APPLYFORSUBMIT_STRONG;
          case 14: return APPROVESUBMIT_STRONG;
          case 15: return SUB_SUCCESS_STRONG;
          case 16: return SUB_FAIL_STRONG;
          case 17: return WHOLE_SUCCESS_STRONG;
          case 18: return WHOLE_FAIL_STRONG;
          case 19: return ADD_ASYNC;
          case 20: return ADD_SUCCESS_ASYNC;
          case 21: return ADD_FAIL_ASYNC;
          case 22: return ASYNC_COMMIT;
          case 23: return ASYNC_CANCEL;
          case 24: return COMMIT_SUCCESS_ASYNC;
          case 25: return WHOLE_SUCCESS_STRONG_ACK;
          case 26: return WHOLE_FAIL_STRONG_ACK;
          case 27: return SUB_SUCCESS;
          case 28: return SUB_FAIL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ActionType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ActionType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ActionType>() {
              public ActionType findValueByNumber(int number) {
                return ActionType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return Message.getDescriptor().getEnumTypes().get(0);
      }

      private static final ActionType[] VALUES = values();

      public static ActionType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ActionType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:Message.ActionType)
    }

    private int bitField0_;
    // optional int32 crcCode = 1;
    public static final int CRCCODE_FIELD_NUMBER = 1;
    private int crcCode_;
    /**
     * <code>optional int32 crcCode = 1;</code>
     */
    public boolean hasCrcCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 crcCode = 1;</code>
     */
    public int getCrcCode() {
      return crcCode_;
    }

    // optional int32 length = 2;
    public static final int LENGTH_FIELD_NUMBER = 2;
    private int length_;
    /**
     * <code>optional int32 length = 2;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 length = 2;</code>
     */
    public int getLength() {
      return length_;
    }

    // optional int64 sessionID = 3;
    public static final int SESSIONID_FIELD_NUMBER = 3;
    private long sessionID_;
    /**
     * <code>optional int64 sessionID = 3;</code>
     */
    public boolean hasSessionID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 sessionID = 3;</code>
     */
    public long getSessionID() {
      return sessionID_;
    }

    // optional int32 type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    /**
     * <code>optional int32 type = 4;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 type = 4;</code>
     */
    public int getType() {
      return type_;
    }

    // optional int32 priority = 5;
    public static final int PRIORITY_FIELD_NUMBER = 5;
    private int priority_;
    /**
     * <code>optional int32 priority = 5;</code>
     */
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 priority = 5;</code>
     */
    public int getPriority() {
      return priority_;
    }

    // optional string id = 6;
    public static final int ID_FIELD_NUMBER = 6;
    private Object id_;
    /**
     * <code>optional string id = 6;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string id = 6;</code>
     */
    public String getId() {
      Object ref = id_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 6;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string info = 7;
    public static final int INFO_FIELD_NUMBER = 7;
    private Object info_;
    /**
     * <code>optional string info = 7;</code>
     */
    public boolean hasInfo() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional string info = 7;</code>
     */
    public String getInfo() {
      Object ref = info_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          info_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string info = 7;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      Object ref = info_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional .Message.ActionType action = 8 [default = DEFAULT];
    public static final int ACTION_FIELD_NUMBER = 8;
    private ActionType action_;
    /**
     * <code>optional .Message.ActionType action = 8 [default = DEFAULT];</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional .Message.ActionType action = 8 [default = DEFAULT];</code>
     */
    public ActionType getAction() {
      return action_;
    }

    private void initFields() {
      crcCode_ = 0;
      length_ = 0;
      sessionID_ = 0L;
      type_ = 0;
      priority_ = 0;
      id_ = "";
      info_ = "";
      action_ = ActionType.DEFAULT;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, crcCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, length_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, sessionID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, priority_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, getInfoBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeEnum(8, action_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, crcCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, length_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, sessionID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, priority_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getIdBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, getInfoBytes());
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, action_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProto.internal_static_Message_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProto.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using com.coconason.dtf.common.protobuf.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        crcCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        priority_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        info_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        action_ = ActionType.DEFAULT;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProto.internal_static_Message_descriptor;
      }

      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Message buildPartial() {
        Message result = new Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.crcCode_ = crcCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionID_ = sessionID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.priority_ = priority_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.info_ = info_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.action_ = action_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (other.hasCrcCode()) {
          setCrcCode(other.getCrcCode());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasSessionID()) {
          setSessionID(other.getSessionID());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        if (other.hasId()) {
          bitField0_ |= 0x00000020;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasInfo()) {
          bitField0_ |= 0x00000040;
          info_ = other.info_;
          onChanged();
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 crcCode = 1;
      private int crcCode_ ;
      /**
       * <code>optional int32 crcCode = 1;</code>
       */
      public boolean hasCrcCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 crcCode = 1;</code>
       */
      public int getCrcCode() {
        return crcCode_;
      }
      /**
       * <code>optional int32 crcCode = 1;</code>
       */
      public Builder setCrcCode(int value) {
        bitField0_ |= 0x00000001;
        crcCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 crcCode = 1;</code>
       */
      public Builder clearCrcCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        crcCode_ = 0;
        onChanged();
        return this;
      }

      // optional int32 length = 2;
      private int length_ ;
      /**
       * <code>optional int32 length = 2;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 length = 2;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <code>optional int32 length = 2;</code>
       */
      public Builder setLength(int value) {
        bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 length = 2;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0;
        onChanged();
        return this;
      }

      // optional int64 sessionID = 3;
      private long sessionID_ ;
      /**
       * <code>optional int64 sessionID = 3;</code>
       */
      public boolean hasSessionID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 sessionID = 3;</code>
       */
      public long getSessionID() {
        return sessionID_;
      }
      /**
       * <code>optional int64 sessionID = 3;</code>
       */
      public Builder setSessionID(long value) {
        bitField0_ |= 0x00000004;
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sessionID = 3;</code>
       */
      public Builder clearSessionID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionID_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 type = 4;
      private int type_ ;
      /**
       * <code>optional int32 type = 4;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 type = 4;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 4;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 4;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }

      // optional int32 priority = 5;
      private int priority_ ;
      /**
       * <code>optional int32 priority = 5;</code>
       */
      public boolean hasPriority() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 priority = 5;</code>
       */
      public int getPriority() {
        return priority_;
      }
      /**
       * <code>optional int32 priority = 5;</code>
       */
      public Builder setPriority(int value) {
        bitField0_ |= 0x00000010;
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 priority = 5;</code>
       */
      public Builder clearPriority() {
        bitField0_ = (bitField0_ & ~0x00000010);
        priority_ = 0;
        onChanged();
        return this;
      }

      // optional string id = 6;
      private Object id_ = "";
      /**
       * <code>optional string id = 6;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string id = 6;</code>
       */
      public String getId() {
        Object ref = id_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string id = 6;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 6;</code>
       */
      public Builder setId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 6;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000020);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 6;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        id_ = value;
        onChanged();
        return this;
      }

      // optional string info = 7;
      private Object info_ = "";
      /**
       * <code>optional string info = 7;</code>
       */
      public boolean hasInfo() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string info = 7;</code>
       */
      public String getInfo() {
        Object ref = info_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          info_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string info = 7;</code>
       */
      public com.google.protobuf.ByteString
          getInfoBytes() {
        Object ref = info_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          info_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string info = 7;</code>
       */
      public Builder setInfo(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        info_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 7;</code>
       */
      public Builder clearInfo() {
        bitField0_ = (bitField0_ & ~0x00000040);
        info_ = getDefaultInstance().getInfo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string info = 7;</code>
       */
      public Builder setInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        info_ = value;
        onChanged();
        return this;
      }

      // optional .Message.ActionType action = 8 [default = DEFAULT];
      private ActionType action_ = ActionType.DEFAULT;
      /**
       * <code>optional .Message.ActionType action = 8 [default = DEFAULT];</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional .Message.ActionType action = 8 [default = DEFAULT];</code>
       */
      public ActionType getAction() {
        return action_;
      }
      /**
       * <code>optional .Message.ActionType action = 8 [default = DEFAULT];</code>
       */
      public Builder setAction(ActionType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000080;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .Message.ActionType action = 8 [default = DEFAULT];</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000080);
        action_ = ActionType.DEFAULT;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Message)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rMessage.proto\"\315\005\n\007Message\022\017\n\007crcCode\030\001" +
      " \001(\005\022\016\n\006length\030\002 \001(\005\022\021\n\tsessionID\030\003 \001(\003\022" +
      "\014\n\004type\030\004 \001(\005\022\020\n\010priority\030\005 \001(\005\022\n\n\002id\030\006 " +
      "\001(\t\022\014\n\004info\030\007 \001(\t\022,\n\006action\030\010 \001(\0162\023.Mess" +
      "age.ActionType:\007DEFAULT\"\245\004\n\nActionType\022\007" +
      "\n\003ADD\020\001\022\022\n\016APPLYFORSUBMIT\020\002\022\021\n\rAPPROVESU" +
      "BMIT\020\003\022\n\n\006CANCEL\020\004\022\013\n\007SUCCESS\020\005\022\010\n\004FAIL\020" +
      "\006\022\013\n\007DEFAULT\020\007\022\r\n\tLOGIN_REQ\020\010\022\016\n\nLOGIN_R" +
      "ESP\020\t\022\021\n\rHEARTBEAT_REQ\020\n\022\022\n\016HEARTBEAT_RE" +
      "SP\020\013\022\016\n\nADD_STRONG\020\014\022\031\n\025APPLYFORSUBMIT_S",
      "TRONG\020\r\022\030\n\024APPROVESUBMIT_STRONG\020\016\022\026\n\022SUB" +
      "_SUCCESS_STRONG\020\017\022\023\n\017SUB_FAIL_STRONG\020\020\022\030" +
      "\n\024WHOLE_SUCCESS_STRONG\020\021\022\025\n\021WHOLE_FAIL_S" +
      "TRONG\020\022\022\r\n\tADD_ASYNC\020\023\022\025\n\021ADD_SUCCESS_AS" +
      "YNC\020\024\022\022\n\016ADD_FAIL_ASYNC\020\025\022\020\n\014ASYNC_COMMI" +
      "T\020\026\022\020\n\014ASYNC_CANCEL\020\027\022\030\n\024COMMIT_SUCCESS_" +
      "ASYNC\020\030\022\034\n\030WHOLE_SUCCESS_STRONG_ACK\020\031\022\031\n" +
      "\025WHOLE_FAIL_STRONG_ACK\020\032\022\017\n\013SUB_SUCCESS\020" +
      "\033\022\014\n\010SUB_FAIL\020\034B1\n!com.coconason.dtf.com" +
      "mon.protobufB\014MessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Message_descriptor,
              new String[] { "CrcCode", "Length", "SessionID", "Type", "Priority", "Id", "Info", "Action", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
