// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Message.proto

package com.coconason.dtf.common.protobuf;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 crcCode = 100001;
    /**
     * <code>optional int32 crcCode = 100001;</code>
     */
    boolean hasCrcCode();
    /**
     * <code>optional int32 crcCode = 100001;</code>
     */
    int getCrcCode();

    // optional int32 length = 100002;
    /**
     * <code>optional int32 length = 100002;</code>
     */
    boolean hasLength();
    /**
     * <code>optional int32 length = 100002;</code>
     */
    int getLength();

    // optional int64 sessionID = 100003;
    /**
     * <code>optional int64 sessionID = 100003;</code>
     */
    boolean hasSessionID();
    /**
     * <code>optional int64 sessionID = 100003;</code>
     */
    long getSessionID();

    // optional int32 type = 100004;
    /**
     * <code>optional int32 type = 100004;</code>
     */
    boolean hasType();
    /**
     * <code>optional int32 type = 100004;</code>
     */
    int getType();

    // optional int32 priority = 100005;
    /**
     * <code>optional int32 priority = 100005;</code>
     */
    boolean hasPriority();
    /**
     * <code>optional int32 priority = 100005;</code>
     */
    int getPriority();

    // optional bytes data = 100006;
    /**
     * <code>optional bytes data = 100006;</code>
     */
    boolean hasData();
    /**
     * <code>optional bytes data = 100006;</code>
     */
    com.google.protobuf.ByteString getData();

    // optional int32 action = 100007;
    /**
     * <code>optional int32 action = 100007;</code>
     */
    boolean hasAction();
    /**
     * <code>optional int32 action = 100007;</code>
     */
    int getAction();

    // optional int64 key = 100008;
    /**
     * <code>optional int64 key = 100008;</code>
     */
    boolean hasKey();
    /**
     * <code>optional int64 key = 100008;</code>
     */
    long getKey();
  }
  /**
   * Protobuf type {@code Message}
   */
  public static final class Message extends
      com.google.protobuf.GeneratedMessage
      implements MessageOrBuilder {
    // Use Message.newBuilder() to construct.
    private Message(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Message(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Message defaultInstance;
    public static Message getDefaultInstance() {
      return defaultInstance;
    }

    public Message getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Message(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 800008: {
              bitField0_ |= 0x00000001;
              crcCode_ = input.readInt32();
              break;
            }
            case 800016: {
              bitField0_ |= 0x00000002;
              length_ = input.readInt32();
              break;
            }
            case 800024: {
              bitField0_ |= 0x00000004;
              sessionID_ = input.readInt64();
              break;
            }
            case 800032: {
              bitField0_ |= 0x00000008;
              type_ = input.readInt32();
              break;
            }
            case 800040: {
              bitField0_ |= 0x00000010;
              priority_ = input.readInt32();
              break;
            }
            case 800050: {
              bitField0_ |= 0x00000020;
              data_ = input.readBytes();
              break;
            }
            case 800056: {
              bitField0_ |= 0x00000040;
              action_ = input.readInt32();
              break;
            }
            case 800064: {
              bitField0_ |= 0x00000080;
              key_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MessageProto.internal_static_Message_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MessageProto.internal_static_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Message.class, Builder.class);
    }

    public static com.google.protobuf.Parser<Message> PARSER =
        new com.google.protobuf.AbstractParser<Message>() {
      public Message parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Message(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Message> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 crcCode = 100001;
    public static final int CRCCODE_FIELD_NUMBER = 100001;
    private int crcCode_;
    /**
     * <code>optional int32 crcCode = 100001;</code>
     */
    public boolean hasCrcCode() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 crcCode = 100001;</code>
     */
    public int getCrcCode() {
      return crcCode_;
    }

    // optional int32 length = 100002;
    public static final int LENGTH_FIELD_NUMBER = 100002;
    private int length_;
    /**
     * <code>optional int32 length = 100002;</code>
     */
    public boolean hasLength() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 length = 100002;</code>
     */
    public int getLength() {
      return length_;
    }

    // optional int64 sessionID = 100003;
    public static final int SESSIONID_FIELD_NUMBER = 100003;
    private long sessionID_;
    /**
     * <code>optional int64 sessionID = 100003;</code>
     */
    public boolean hasSessionID() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int64 sessionID = 100003;</code>
     */
    public long getSessionID() {
      return sessionID_;
    }

    // optional int32 type = 100004;
    public static final int TYPE_FIELD_NUMBER = 100004;
    private int type_;
    /**
     * <code>optional int32 type = 100004;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int32 type = 100004;</code>
     */
    public int getType() {
      return type_;
    }

    // optional int32 priority = 100005;
    public static final int PRIORITY_FIELD_NUMBER = 100005;
    private int priority_;
    /**
     * <code>optional int32 priority = 100005;</code>
     */
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 priority = 100005;</code>
     */
    public int getPriority() {
      return priority_;
    }

    // optional bytes data = 100006;
    public static final int DATA_FIELD_NUMBER = 100006;
    private com.google.protobuf.ByteString data_;
    /**
     * <code>optional bytes data = 100006;</code>
     */
    public boolean hasData() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional bytes data = 100006;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    // optional int32 action = 100007;
    public static final int ACTION_FIELD_NUMBER = 100007;
    private int action_;
    /**
     * <code>optional int32 action = 100007;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional int32 action = 100007;</code>
     */
    public int getAction() {
      return action_;
    }

    // optional int64 key = 100008;
    public static final int KEY_FIELD_NUMBER = 100008;
    private long key_;
    /**
     * <code>optional int64 key = 100008;</code>
     */
    public boolean hasKey() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional int64 key = 100008;</code>
     */
    public long getKey() {
      return key_;
    }

    private void initFields() {
      crcCode_ = 0;
      length_ = 0;
      sessionID_ = 0L;
      type_ = 0;
      priority_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
      action_ = 0;
      key_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(100001, crcCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(100002, length_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(100003, sessionID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(100004, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(100005, priority_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(100006, data_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeInt32(100007, action_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeInt64(100008, key_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(100001, crcCode_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(100002, length_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(100003, sessionID_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(100004, type_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(100005, priority_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(100006, data_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(100007, action_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(100008, key_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Message parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Message parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Message parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Message parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Message parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Message parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Message parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Message prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Message}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MessageProto.internal_static_Message_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MessageProto.internal_static_Message_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Message.class, Builder.class);
      }

      // Construct using com.coconason.dtf.common.protobuf.MessageProto.Message.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        crcCode_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        length_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        sessionID_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        priority_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        data_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000020);
        action_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        key_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000080);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MessageProto.internal_static_Message_descriptor;
      }

      public Message getDefaultInstanceForType() {
        return Message.getDefaultInstance();
      }

      public Message build() {
        Message result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Message buildPartial() {
        Message result = new Message(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.crcCode_ = crcCode_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.length_ = length_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sessionID_ = sessionID_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.priority_ = priority_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.data_ = data_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.key_ = key_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Message) {
          return mergeFrom((Message)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Message other) {
        if (other == Message.getDefaultInstance()) return this;
        if (other.hasCrcCode()) {
          setCrcCode(other.getCrcCode());
        }
        if (other.hasLength()) {
          setLength(other.getLength());
        }
        if (other.hasSessionID()) {
          setSessionID(other.getSessionID());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        if (other.hasData()) {
          setData(other.getData());
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasKey()) {
          setKey(other.getKey());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Message parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Message) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 crcCode = 100001;
      private int crcCode_ ;
      /**
       * <code>optional int32 crcCode = 100001;</code>
       */
      public boolean hasCrcCode() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 crcCode = 100001;</code>
       */
      public int getCrcCode() {
        return crcCode_;
      }
      /**
       * <code>optional int32 crcCode = 100001;</code>
       */
      public Builder setCrcCode(int value) {
        bitField0_ |= 0x00000001;
        crcCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 crcCode = 100001;</code>
       */
      public Builder clearCrcCode() {
        bitField0_ = (bitField0_ & ~0x00000001);
        crcCode_ = 0;
        onChanged();
        return this;
      }

      // optional int32 length = 100002;
      private int length_ ;
      /**
       * <code>optional int32 length = 100002;</code>
       */
      public boolean hasLength() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 length = 100002;</code>
       */
      public int getLength() {
        return length_;
      }
      /**
       * <code>optional int32 length = 100002;</code>
       */
      public Builder setLength(int value) {
        bitField0_ |= 0x00000002;
        length_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 length = 100002;</code>
       */
      public Builder clearLength() {
        bitField0_ = (bitField0_ & ~0x00000002);
        length_ = 0;
        onChanged();
        return this;
      }

      // optional int64 sessionID = 100003;
      private long sessionID_ ;
      /**
       * <code>optional int64 sessionID = 100003;</code>
       */
      public boolean hasSessionID() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 sessionID = 100003;</code>
       */
      public long getSessionID() {
        return sessionID_;
      }
      /**
       * <code>optional int64 sessionID = 100003;</code>
       */
      public Builder setSessionID(long value) {
        bitField0_ |= 0x00000004;
        sessionID_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 sessionID = 100003;</code>
       */
      public Builder clearSessionID() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sessionID_ = 0L;
        onChanged();
        return this;
      }

      // optional int32 type = 100004;
      private int type_ ;
      /**
       * <code>optional int32 type = 100004;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 type = 100004;</code>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 100004;</code>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 100004;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }

      // optional int32 priority = 100005;
      private int priority_ ;
      /**
       * <code>optional int32 priority = 100005;</code>
       */
      public boolean hasPriority() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 priority = 100005;</code>
       */
      public int getPriority() {
        return priority_;
      }
      /**
       * <code>optional int32 priority = 100005;</code>
       */
      public Builder setPriority(int value) {
        bitField0_ |= 0x00000010;
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 priority = 100005;</code>
       */
      public Builder clearPriority() {
        bitField0_ = (bitField0_ & ~0x00000010);
        priority_ = 0;
        onChanged();
        return this;
      }

      // optional bytes data = 100006;
      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes data = 100006;</code>
       */
      public boolean hasData() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional bytes data = 100006;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <code>optional bytes data = 100006;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes data = 100006;</code>
       */
      public Builder clearData() {
        bitField0_ = (bitField0_ & ~0x00000020);
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }

      // optional int32 action = 100007;
      private int action_ ;
      /**
       * <code>optional int32 action = 100007;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 action = 100007;</code>
       */
      public int getAction() {
        return action_;
      }
      /**
       * <code>optional int32 action = 100007;</code>
       */
      public Builder setAction(int value) {
        bitField0_ |= 0x00000040;
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 action = 100007;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000040);
        action_ = 0;
        onChanged();
        return this;
      }

      // optional int64 key = 100008;
      private long key_ ;
      /**
       * <code>optional int64 key = 100008;</code>
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int64 key = 100008;</code>
       */
      public long getKey() {
        return key_;
      }
      /**
       * <code>optional int64 key = 100008;</code>
       */
      public Builder setKey(long value) {
        bitField0_ |= 0x00000080;
        key_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 key = 100008;</code>
       */
      public Builder clearKey() {
        bitField0_ = (bitField0_ & ~0x00000080);
        key_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Message)
    }

    static {
      defaultInstance = new Message(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Message)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Message_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Message_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rMessage.proto\"\230\001\n\007Message\022\021\n\007crcCode\030\241" +
      "\215\006 \001(\005\022\020\n\006length\030\242\215\006 \001(\005\022\023\n\tsessionID\030\243\215" +
      "\006 \001(\003\022\016\n\004type\030\244\215\006 \001(\005\022\022\n\010priority\030\245\215\006 \001(" +
      "\005\022\016\n\004data\030\246\215\006 \001(\014\022\020\n\006action\030\247\215\006 \001(\005\022\r\n\003k" +
      "ey\030\250\215\006 \001(\003B1\n!com.coconason.dtf.common.p" +
      "rotobufB\014MessageProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Message_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Message_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Message_descriptor,
              new String[] { "CrcCode", "Length", "SessionID", "Type", "Priority", "Data", "Action", "Key", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
