package com.coconason.dtf.demo2.po;

import java.io.Serializable;

public class Teacher implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.T
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private Integer t;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Teacher.Tname
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private String tname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table Teacher
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.T
     *
     * @return the value of Teacher.T
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public Integer getT() {
        return t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.T
     *
     * @param t the value for Teacher.T
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public void setT(Integer t) {
        this.t = t;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Teacher.Tname
     *
     * @return the value of Teacher.Tname
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Teacher.Tname
     *
     * @param tname the value for Teacher.Tname
     *
     * @mbggenerated Mon Aug 27 14:24:30 CST 2018
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }
}